extension_dir="C:\Users\MUHAMMAD UBAID\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension=mysqli
extension=mbstring
extension=openssl
extension=curl
extension=pdo_mysql
date.timezone=Asia/Karachi
session.save_path="C:\Users\MUHAMMAD UBAID\Documents\GitHub\DBS Project\.sessions"
display_errors=On
log_errors=On
